
import React from 'react';
import { Play, FileText, CheckCircle, BarChart, Settings } from 'lucide-react';
import ScrollReveal from './ScrollReveal';

interface UserGuideProps {
  onNavigate: () => void;
}

const UserGuide: React.FC<UserGuideProps> = ({ onNavigate }) => {
  const steps = [
      {
          icon: <Settings size={20} className="text-[#FFCB74]" />,
          title: "1. Define Job Context",
          content: "Before uploading resumes, enter the 'Target Job Role' in the configuration panel. This tells the AI what to look for. For example, 'Senior React Developer' will trigger a different scoring weighting than 'Project Manager'."
      },
      {
          icon: <FileText size={20} className="text-[#FFCB74]" />,
          title: "2. Upload Resumes",
          content: "Drag and drop your PDF files into the upload zone. You can upload multiple files at once. The system will queue them up. Currently, we recommend batches of 10-20 for optimal browser performance."
      },
      {
          icon: <Play size={20} className="text-[#FFCB74]" />,
          title: "3. Start Analysis",
          content: "Click the 'Start Queue' button. ALIGN will process files one by one. You will see a progress bar and status indicators change from 'Queued' to 'Processing' to 'Completed'."
      },
      {
          icon: <BarChart size={20} className="text-[#FFCB74]" />,
          title: "4. Review Results",
          content: "As analysis completes, cards will appear below. Each card contains a pass/fail tag, a fit score (0-100), and a detailed breakdown of Strengths and Weaknesses generated by the AI."
      }
  ];

  return (
    <div className="pt-32 pb-24 px-6 min-h-[80vh] max-w-5xl mx-auto">
      <ScrollReveal direction="down" className="text-center mb-16">
        <h1 className="text-4xl md:text-6xl font-bold mb-6 tracking-tight">
            User <span className="gold-gradient-text">Guide</span>
        </h1>
        <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            Master the ALIGN platform in minutes. Follow this step-by-step tutorial to start screening candidates effectively.
        </p>
      </ScrollReveal>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-12 relative">
          {/* Vertical Line for Desktop */}
          <div className="hidden md:block absolute left-1/2 top-0 bottom-0 w-px bg-[#2F2F2F] -translate-x-1/2"></div>

          {steps.map((step, index) => (
              <ScrollReveal 
                key={index} 
                direction={index % 2 === 0 ? "right" : "left"} 
                className={`flex flex-col gap-4 ${index % 2 !== 0 ? 'md:mt-24' : ''}`}
              >
                  <div className="bg-[#1a1a1a] border border-[#2F2F2F] rounded-2xl p-8 hover:border-[#FFCB74]/30 transition-all relative z-10">
                      <div className="w-12 h-12 bg-[#111] rounded-xl flex items-center justify-center mb-4 border border-[#2F2F2F] shadow-lg">
                          {step.icon}
                      </div>
                      <h3 className="text-xl font-bold text-white mb-3">{step.title}</h3>
                      <p className="text-gray-400 leading-relaxed text-sm">
                          {step.content}
                      </p>
                  </div>
              </ScrollReveal>
          ))}
      </div>

      <ScrollReveal direction="up" className="mt-20 bg-[#FFCB74]/10 border border-[#FFCB74]/20 rounded-2xl p-8 flex flex-col md:flex-row items-center justify-between gap-6">
          <div>
              <h3 className="text-xl font-bold text-[#FFCB74] mb-2">Ready to try it out?</h3>
              <p className="text-gray-300 text-sm">Jump straight into the tool and run your first batch.</p>
          </div>
          <button onClick={() => window.location.href='/#products'} className="bg-[#FFCB74] text-[#111111] px-6 py-3 rounded-full font-bold hover:bg-[#eebb55] transition-colors whitespace-nowrap">
              Go to Tools
          </button>
      </ScrollReveal>
    </div>
  );
};

export default UserGuide;
    